sudo: required
language: java
dist: trusty



cache:
  directories:
  - $HOME/.m2
      
script: robot buy_contract.robot

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
 - sudo apt-get install -y libnss3 libgconf-2-4
 - sudo python -m pip install robotframework
 - sudo pip install --upgrade --pre robotframework-selenium2library
 
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"


  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - ehtesham@binary.com
    on_success: never
    on_failure: always